### PR TITLE
Update core templates and cleanup

### PR DESCRIPTION
**Pull request by sinedied**
Updated all core templates and removed unused bicep files

cc @tonybaloney

### CODE REVIEW

**Comment by tonybaloney** [comment]
please restore `main.test.bicep`

**Comment by sinedied** [comment]
Oops, done!

**Comment by greenie-msft** [comment]
@tonybaloney, @sinedied, do these changes successfully deploy for you? I'm noticing the app crashes for me after 'azd up'

**Comment by greenie-msft** [comment]
It looks like the checkout service revision is crashing. Can you please fix this or revert the change?

Screenshot 2024-08-02 at 10 43 53 AM

**Comment by sinedied** [comment]
> @tonybaloney, @sinedied, do these changes successfully deploy for you? I'm noticing the app crashes for me after 'azd up'

I successfully deployed the sample before sending in the PR, no crash.
Only the infra was updated, and it was already listening on port 80 before the changes, so I'm not sure the changes caused this.

**Comment by greenie-msft** [comment]
@sinedied sorry, but I just tested this again. 

If I checkout this commit (347d8ae123fed8149fa60ff82f9811592e3ff3fc) before your introduced changes and 'azd up' the app works as expected. 
Screenshot 2024-08-06 at 11 18 43 AM

If I deploy latest on main after your PR, it causes the app to crash. 

Can you please confirm that you see this behavior as well? I think it might have something to do with the container app infra changes that you made.

**Comment by sinedied** [comment]
@greenie-msft I'm sorry I currently don't have a subscription at hand where I can test deploy it, but reading through the PR again it might just need a small fix dues to default parameters that changed. I've opened a PR, please test it if it solves the issue: https://github.com/Azure-Samples/svc-invoke-dapr-nodejs/pull/9

**Pull request merged**
